services:
  database:
    image: postgres:14.1
    environment:
      POSTGRES_DB: example
      POSTGRES_USER: example
      POSTGRES_PASSWORD: example
    volumes:
      - ./database/migrations:/docker-entrypoint-initdb.d
