services:
  zookeeper:
    image: debezium/zookeeper:1.7
    ports:
     - 2181:2181
     - 2888:2888
     - 3888:3888

  kafka:
    image: debezium/kafka:1.7
    ports:
     - 9092:9092
    links:
     - zookeeper
    environment:
     - ZOOKEEPER_CONNECT=zookeeper:2181

  postgres:
    image: debezium/example-postgres:1.7
    ports:
     - 5432:5432
    environment:
     - POSTGRES_USER=postgres
     - POSTGRES_PASSWORD=postgres

  connect:
    image: debezium/connect:1.7
    ports:
     - 8083:8083
    links:
     - kafka
     - postgres
    environment:
     - BOOTSTRAP_SERVERS=kafka:9092
     - GROUP_ID=1
     - CONFIG_STORAGE_TOPIC=my_connect_configs
     - OFFSET_STORAGE_TOPIC=my_connect_offsets
     - STATUS_STORAGE_TOPIC=my_connect_statuses

  stock-notifier:
    build:
      context: ./stock-notifier

  psql:
    image: debezium/example-postgres:1.7
    profiles:
      - tools
    links:
      - postgres
    command: ["psql", "host=postgres user=postgres password=postgres dbname=postgres options=--search_path=inventory"]

  watch-topic:
    image: debezium/kafka:1.7
    profiles:
      - tools
    links:
     - zookeeper
     - kafka
    environment:
      - ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_BROKER=kafka:9092
    entrypoint: ["/docker-entrypoint.sh", "watch-topic", "-a", "-k"]
